# Generated by Django 4.2 on 2024-12-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_topic_news_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='topic',
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.topic'),
        ),
    ]
