# Generated by Django 4.2 on 2024-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_news_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-published_date',), 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='contact',
            name='creator',
            field=models.BooleanField(default=False),
        ),
    ]
