# Generated by Django 4.2 on 2024-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_news_options_contact_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/defaultPost.jpg', upload_to='news/% Y/% m/% d/'),
        ),
    ]
