# Generated by Django 5.1.4 on 2024-12-19 12:14

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_news_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
